name: Update Last Online Badge

on:
  schedule:
    # Run daily
    - cron: "0 0 * * *"
  workflow_dispatch: # Allow manual trigger

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Calculate Elapsed Time
        id: elapsed-time
        run: |
          # Get the last commit timestamp
          last_commit_time=$(git log -1 --format=%ct || echo "0")
          current_time=$(date +%s)
          elapsed_seconds=$((current_time - last_commit_time))

          # Convert to days, hours, and minutes
          days=$((elapsed_seconds / 86400))
          hours=$(( (elapsed_seconds % 86400) / 3600 ))
          minutes=$(( (elapsed_seconds % 3600) / 60 ))

          # Format the elapsed time
          elapsed="last ${days}d ${hours}hrs ${minutes}mins"
          echo "elapsed_time=$elapsed" >> $GITHUB_ENV
          echo "$elapsed" > elapsed_time.txt

      - name: Display Elapsed Time (Debug)
        run: |
          echo "Elapsed Time: ${{ env.elapsed_time }}"

      - name: Update JSON File
        run: |
          elapsed_time=$(cat elapsed_time.txt)
          echo "{
            \"schemaVersion\": 1,
            \"label\": \"Last Online\",
            \"message\": \"$elapsed_time\",
            \"color\": \"blue\"
          }" > last_online.json

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add last_online.json
          git commit -m "Updated Last Online Badge" || echo "No changes to commit"
          git push || echo "Nothing to push, changes already up-to-date"
